/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paperfish_jnitest_myJNI */

#ifndef _Included_com_paperfish_jnitest_myJNI
#define _Included_com_paperfish_jnitest_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paperfish_jnitest_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_paperfish_jnitest_myJNI_sayHello
  (JNIEnv *env, jclass jobj){
    return (*env)->NewStringUTF(env,"JNI HELLO!");

  }

#ifdef __cplusplus
}
#endif
#endif
