/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ssdut_lst_testjni_TestJni */

#ifndef _Included_cn_ssdut_lst_testjni_TestJni
#define _Included_cn_ssdut_lst_testjni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ssdut_lst_testjni_TestJni
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_ssdut_lst_testjni_TestJni_Init
  (JNIEnv *, jobject);

/*
 * Class:     cn_ssdut_lst_testjni_TestJni
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_ssdut_lst_testjni_TestJni_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cn_ssdut_lst_testjni_TestJni
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_ssdut_lst_testjni_TestJni_Destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
